name: Build Kernel
# Did you edit build file first? If not, edit it.
on: 
  workflow_dispatch:
    inputs:
      DEVICE_NAME:
        description: 'Your device codename.'
        required: true
        default: ''
      ANDROID_VERSION:
        description: 'Your android version.'
        required: true
        default: ''
        type: choice
        options:
        - s-oss
        - r-oss
        - q-oss
        - o-oss
        - n-oss
        - m-oss

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set Properties # Output will be use in final name of recovery.
      id: props
      run: |
        echo "date=$(TZ=Asia/Manila date +%Y%m%d-%I%M%p)" >> $GITHUB_OUTPUT
      
    - name: Start Building Kernel
      run: |
        ./build

    - name: Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: |
          /home/runner/work/ANY/*.zip
          /home/runner/work/myKernel/out/arch/arm64/boot/*.zip
        name: Custom Kernel - Build ${{ steps.props.outputs.date }}
        draft: false
        prerelease: true
        tag: ${{ github.run_id }}-${{ steps.props.outputs.date }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## Custom Kernel via Github Actions for ${{ github.event.inputs.DEVICE_NAME }}-${{ github.event.inputs.ANDROID_VERSION }}
          - Notes:
            - Uploaded AnyKernel3.zip (without kernel inside) and myKernel-xxxxxx.zip with your newly-compiled kernel inside.
            - Read my instruction below first.
          - Flash:
            - Download AnyKernel3.zip and myKernel-xxxxxxx.zip (whatever the name was), extract both.
            - Copy a kernel (could be Image, Image-dtb, Image.gz-dtb, pick one) inside myKernel-xxxxxxx folder, and paste it in AnyKernel3 folder and compressed it.
            - Flash it via twrp or magisk.

    - name: Link of Release
      run: |
        echo "Enjoy your Newly Built Kernel"
        echo "https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ github.run_id }}-${{ steps.props.outputs.date }}"
